// <auto-generated />
namespace PlanMyRun.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddedZipCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedZipCode));
        
        string IMigrationMetadata.Id
        {
            get { return "202004011544077_AddedZipCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
